audit_header: false
title: Tampa Bay Real Estate Video Blog with Karen & Joe Donovan
description: Our mission at Donovan Home Sales, Inc. is to be your best resource for Tampa Bay real estate advice. Whether you are a buyer, seller, or investor, our team of professionals can answer any questions you might have about real estate. If you are looking to buy or sell a home, you can get all the information and the latest updates, tips, and tricks from The Donovan Home Sales, Inc., your professional Tampa Bay Real Estate Agents.
show_custom_links: false
custom_links:
  - title:
    url:
show_custom_links_new_tab: false
custom_links_new_tab:
  - title:
    url:

client:
  name: Karen & Joe Donovan
  title:
  license_number:
  about_markdown: |
    Donovan Home Sales, Inc., founded in 2000, is built on a strong foundation of core values and purpose. We operate in a fun, exciting and challenging environment that helps all of us achieve our goals. Each of our staff members and agents are dedicated to teamwork, self-improvement, positive attitudes and most importantly, a passion and drive to surpass the expectations of every client who does business with us. Whether you are looking to sell your home, or purchase a new one, we can offer a dedicated professional team and an innovative on-line approach.

    Our team of enthusiastic, hard working real estate agents is ready to walk you through the process of buying the perfect home or selling your existing house for the best price.

    Joe and Karen Donovan, Broker –Owners, have been helping families in the Tampa Bay - St. Pete/Clearwater area for over 20 years. Joe & Karen and their team have participated in helping over 1000 families turn their real estate dreams and goals into reality.
  brand: Donovan Home Sales, Inc.
  brokerage:
  market: Tampa Bay
  address: 801 West Bay Dr. 122<br>Largo, FL 33770
  phone: 727-595-8880
  phone_type:
  phone2:
  phone2_type:
  email: Karen@homesbydonovan.com
  url: http://www.StPeteClearWaterMLS.com

CTAs:
  first_CTA_text: Home Valuation
  first_CTA_URL: http://www.tampabayhomeslist.com/cma/property-valuation/
  second_CTA_text: Home Search
  second_CTA_URL: http://www.tampabayhomeslist.com/search/advanced_search
  third_CTA_text: Let's Meet
  third_CTA_URL: https://kjdonovan.wufoo.com/forms/zrybf0l08ehaf6/

sidebar_CTA:
  - CTA_image_path: /img/cta-images/001.jpg
    CTA_title: "What’s Your Tampa Bay Home Worth?"
    CTA_text: "Are you thinking of selling your home or interested in learning about home prices in your neighborhood? We can help you."
    CTA_link_text: "Free Home Value Report"
    CTA_url: http://www.tampabayhomeslist.com/cma/property-valuation/

second_sidebar_CTA:
  - CTA_image_path2: /img/cta-images/002.jpg
    CTA_title2: "Looking for a Tampa Bay Home?"
    CTA_text2: "Search the entire MLS for your Tampa Bay home."
    CTA_link_text2: "Search the MLS"
    CTA_url2: http://www.tampabayhomeslist.com/search/advanced_search

third_sidebar_CTA:
  - CTA_image_path3: /img/cta-images/003.jpg
    CTA_title3: "Interested in a career in real estate?"
    CTA_text3: "Set up a Skype or Coffee Meeting."
    CTA_link_text3: "Let's meet!"
    CTA_url3: /meeting/

lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: /img/lender-headshot.jpg
  logo_path: /img/lender-logo.png
  name:
  license_number:
  company:
  company_license_number:
  phone:
  email:
  url:

socials:
  review_sm_icons: false
  facebook_url: https://www.facebook.com/Donovan-Home-Sales-122315191113272
  linkedin_url: https://www.linkedin.com/pub/karen-donovan/27/1a9/657
  youtube_url: https://www.youtube.com/channel/UCSUrltTypgDYDihP0ox8Obg
  twitter_url: http://www.twitter.com/donovanrealty
  instagram_url:
  pinterest_url:
  zillow_url: http://www.zillow.com/profile/Karen-Donovan/
  trulia_url: http://www.trulia.com/profile/karen-donovan-agent-11801-230122/overview
  yelp_url: http://www.yelp.com/biz/donovan-home-sales-inc-tampa-bay
  podcast_url:

podcast:
  title: 'Tampa Bay Real Estate Podcast with Karen & Joe Donovan'
  categories: Education
  image: /img/podcast.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the Tampa Bay Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from Donovan Home Sales, Inc. - your professional Tampa Bay Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in Tampa Bay, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: 'Karen & Joe Donovan'

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 30
  hero_text: Tampa Bay Real Estate Video Blog
  hero_background_hex: '#999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
site_colors:
  brand_color: '#013E7D'
  theme_color: '#4A9FB4'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: black

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: transparent
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
